// Generated by scripts/gen_gba_over.py in game-and-what — DO NOT HAND-EDIT.
// Regenerate there and copy, or the firmware will silently disagree with the
// measurements. See docs/GBA_FIRMWARE_HANDOFF.md.
//
// Every address was measured by running the rom: gpSP demonstrably skips on it.
// Apply after the rom is loaded:
//     extern u32 idle_loop_target_pc;
//     u32 pc = gba_idle_loop_lookup(rom + 0xAC);
//     if (pc) idle_loop_target_pc = pc;

#include "gba_idle_loop.h"

#include <string.h>

typedef struct {
    char code[5];      // the 4 chars at rom[0xAC]
    uint32_t pc;       // the backward branch that closes the wait loop
    uint32_t exec;     // measured CPU cycles/frame, of 280896, with the skip on
} gba_idle_entry_t;

static const gba_idle_entry_t GBA_IDLE_LOOPS[] = {
    { "ADKP", 0x8002f30, 16664 },   // 도날드덕 어드밴스
    { "AFZE", 0x8000c2e, 61334 },   // F-제로 맥시멈 벨로시티 (F-Zero - Maximum Velocity)
    { "APDE", 0x8000300, 63154 },   // 핀볼 오브 데드 (Pinball of the Dead, The)
    { "BDTE", 0x800065a, 65065 },   // 다운타운 열혈물어EX (한글패치)
    { "V49J", 0x80006c2, 66296 },   // 스크류 브레이커
    { "BPYP", 0x80900f2, 68058 },   // 페르시아의 왕자 - 시간의 모래
    { "APLP", 0x80075a6, 68473 },   // 핀볼 챌린지 디럭스 (Pinball Challenge Deluxe)
    { "BTMJ", 0x8013888, 70699 },   // 마리오 테니스 어드밴스 (Mario Tennis Advance)
    { "A7KE", 0x8000fae, 71428 },   // 별의 커비 - 꿈의 샘 디럭스 (Kirby - Nightmare in Dream Land)
    { "BMGE", 0x8014e0a, 71769 },   // 마리오 골프 어드밴스 투어 (Mario Golf - Advance Tour)
    { "BRIJ", 0x80013d4, 75039 },   // 리듬세상 (한글패치)
    { "AAMJ", 0x80003ce, 76293 },   // 캐슬바니아 - 서클 오브 더 문 (한글패치)
    { "BPGE", 0x80008c6, 77946 },   // 포켓몬스터 리프그린 (한글패치, 미국판 헤더)
    { "BPEK", 0x80008ce, 78796 },   // 포켓몬스터 에메랄드 (정식 한국판)
    { "BPRE", 0x80008c6, 78916 },   // 포켓몬스터 파이어레드 (한글패치, 미국판 헤더)
    { "AX4J", 0x8000732, 81845 },   // 슈퍼마리오 브라더스3 (Super Mario Advance 4 - Super Mario 3 + Mario Brothers)
    { "BM5E", 0x8033eec, 87371 },   // 마리오 vs. 동키콩 (Mario vs. Donkey Kong)
    { "AGAE", 0x8013844, 93880 },   // 그라디우스 갤럭시즈 (Gradius Galaxies)
    { "ARZJ", 0x80004f6, 98249 },   // 록맨 제로 1 (Megaman Zero 1)
    { "AGFJ", 0x8013542, 102002 },   // 황금의 태양 2 - 잃어버린 시대 (Ougon no Taiyou - Ushinawareshi Toki)
    { "AREJ", 0x8000338, 106477 },   // 록맨 에그제
    { "BSME", 0x8000298, 111771 },   // 메탈슬러그 어드밴스 (Metal Slug Advance)
    { "B4ZJ", 0x8000914, 115793 },   // 록맨 제로 4 (한글패치)
    { "AFXJ", 0x8000428, 117713 },   // 파이널 판타지 택틱스 어드밴스 (한글패치)
    { "A62J", 0x800066c, 121001 },   // 록맨 제로 2 (Megaman Zero 2)
    { "AA2C", 0x80005ec, 137673 },   // 슈퍼마리오월드 (한글패치)
    { "BZ3J", 0x80019c4, 137998 },   // 록맨 제로 3 (한글패치)
    { "AZWJ", 0x8000f5e, 142521 },   // 메이드 인 와리오 (한글패치)
    { "AZ8E", 0x8002b5e, 152070 },   // 슈퍼 퍼즐파이터II Turbo터보
    { "A3AJ", 0x8002ba4, 175310 },   // 슈퍼마리오 요시아일랜드 (Super Mario Advance 3 - Yoshi's Island + Mario Brothers)
};

uint32_t gba_idle_loop_lookup(const char *gamepak_code) {
    for (size_t i = 0; i < sizeof(GBA_IDLE_LOOPS) / sizeof(GBA_IDLE_LOOPS[0]); ++i) {
        if (memcmp(GBA_IDLE_LOOPS[i].code, gamepak_code, 4) == 0) {
            return GBA_IDLE_LOOPS[i].pc;
        }
    }
    return 0;   // unknown game: leave gpSP's own table alone
}

uint32_t gba_exec_cycles_lookup(const char *gamepak_code) {
    for (size_t i = 0; i < sizeof(GBA_IDLE_LOOPS) / sizeof(GBA_IDLE_LOOPS[0]); ++i) {
        if (memcmp(GBA_IDLE_LOOPS[i].code, gamepak_code, 4) == 0) {
            return GBA_IDLE_LOOPS[i].exec;
        }
    }
    return 0;
}
